#!/usr/bin/env bash

function testexpand {
  echo ""
  echo "test: $1 expected: $2"
  ./expand "$1" | wc -c | grep "$2" && echo "success" || echo "fail"
}

testexpand "a-z" "27"
testexpand "a-b-z" "27"
testexpand "A-z" "4"
testexpand "a-Z" "4"
testexpand "0-9" "11"
testexpand "0-9-" "12"
testexpand "a-b-z-" "28"
testexpand "g-8" "4"
testexpand "00--00-0-" "10"
testexpand "m-j" "4"
