#!/usr/bin/env bash

function test () {
  ./daytab "$1" "$2" "$3" "$4" | grep -e "$5" && echo "success" || echo "fail"
}

# Describe day_of_year
# It should give day 60 for 2/29 on a leap year
test 1988 2 29 0 "60 -1 -1"
# It should give -1 for 2/29 on a non-leap year as that is not a valid day
test 1987 2 29 0 "-1 -1 -1"
# It should give day 366 for 12/31 on a leap year
test 1988 12 31 0 "366 -1 -1"
# It should give day 365 for 12/31 on a non-leap year
test 1987 12 31 0 "365 -1 -1"
# It should give -1 for 12/32 as that is not a valid day
test 1987 12 32 0 "-1 -1 -1"
# It should give -1 for 2/30 as that is not a valid day
test 1987 2 30 0 "-1 -1 -1"
# It should give day 1 for 1/1, and 1/1 for day 1
test 1988 1 1 1 "1 1 1"
# Describe month_day
# It should give 2/29 for day 60 on a leap year
test 1988 1 1 60 "1 2 29"
# It should give 3/1 for day 60 on a non-leap year
test 1987 1 1 60 "1 3 1"
# It should give -1 -1 for day 400, as that is not a valid day.
test 1988 1 1 400 "1 -1 -1"